services:
  mmc-lqmdem:
    build: . 
    container_name: "traefik"
    networks:
      - proxy
    ports:
      - "3000:3000"
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`mmc-bot.ai-man.dev`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=default"
      - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"


networks:
  proxy:
    external: true